spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service?useSSL=false
    username: root
    password: root
    dbcp:
      validation-query: SELECT 1 
      test-on-borrow: true 
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: false
